= KSQL: Run SQL queries on Kubernetes

Runs SQL queries (provided by DuckDB) on Kubernetes JSON outputs.

// The JSON outputs are auto hidrated after 10 mins, or on demand.

High level process occurring behind the scenes:

Run: `ksql get -A pods sts deploy nodes replicasets`
ksql will run: `kubectl pods -o json > pods.json`, save the output into the user's cache dir separated by k8s context.
ksql will run `qq .items` on it to have a single list of results.
ksql will run `duckdb` to import the file and auto discover the schema.

Run: `ksql query`

select metadata.name,ready:list_transform(status.containerStatuses, s ->s.ready) from pods where metadata.name like 'eventbus-%';

select p.metadata.name,ownerName:p.metadata.ownerReferences[1].name,ownerKind:p.metadata.ownerReferences[1].kind from pods as p join sts as s on p.metadata.ownerReferences[1].name == s.metadata.name;


select s.metadata.name,date_diff('days', s.metadata.creationtimestamp, today()) as age,status.readyReplicas,status.replicas from './sts.json' as s;

select s.metadata.name,s.metadata.namespace,status.readyReplicas,status.replicas,age:k8s.age(s) from sts as s;


== Helper Functions

=== k8s

[source, sql]
----
CREATE SCHEMA IF NOT EXISTS k8s;
CREATE FUNCTION IF NOT EXISTS k8s.age(x) AS date_diff('days', x.metadata.creationtimestamp, today());
----
