= KSQL: Run SQL queries on Kubernetes

Runs SQL queries (provided by DuckDB) on Kubernetes JSON outputs.

High level process occurring behind the scenes:

Run: `ksql get -A pods sts deploy nodes replicasets`

ksql will:

* run: `kubectl pods -A -o json > pods.json`, save the output into the user's cache dir separated by k8s context.
* run `qq .items` on the saved output to have a single list of results.
* run `duckdb` to import the file and auto discover the schema.
* Since this tool focuses on k8s, it will surface the `metadata.name` as `name` and `metadata.namespace` as `namespace` for each of the resources imported.
A node will have a `NULL` namespace, for example, but the query will still work.
* create a few handy <<helper-functions>> and <<views>> for you to use.

Now, you can run `ksql query` or call duckdb directly on the created db `duckdb ksql.duckdb`

`ksql query` will print the results as a json stream because vertical scrolling is easier than horizontal scrolling on a terminal.

To re-hidrate your data, you can run the `ksql get` command again with each of the resources you want to hidrate.
The rest will stay in place.

To start over or be done, delete the `ksql.duckdb` file.

== Helpful Queries

* Check schema for the columns of a table:
+
[source, sql]
----
select column_name,data_type from duckdb_columns() where table_name = 'pods';
----

== Helper Functions

=== k8s

This is how the surfacing of name and metadata is done in the code:

[source, go]
----
fmt.Sprintf("ALTER TABLE %s ADD COLUMN name VARCHAR;", rt),
fmt.Sprintf("UPDATE %s SET name = metadata.name;", rt),
fmt.Sprintf("ALTER TABLE %s ADD COLUMN namespace VARCHAR;", rt),
// Use cast to allow for null values
fmt.Sprintf("UPDATE %s SET namespace = CAST(metadata AS JSON)->>'namespace';", rt),
----

Get the age in days of a resource.
`k8s.age(x)` will take the resource directly if you are querying a resource table.
`k8s.mage(x_metadata)` will take the resource metadata alias if you are querying a view.

[source, sql]
----
CREATE SCHEMA IF NOT EXISTS k8s;

CREATE FUNCTION IF NOT EXISTS k8s.age(x) AS date_diff('days', x.metadata.creationtimestamp, today());

CREATE FUNCTION IF NOT EXISTS k8s.mage(x_metadata) AS date_diff('days', x_metadata.creationtimestamp, today());
----

Normalize CPU to m unit so it can be used with aggregation operations:

[source, sql]
----
CREATE OR REPLACE MACRO k8s.cpu_m(cpu) AS
	CASE
		WHEN trim(cpu) LIKE '%m' THEN
			CAST(CEILING(CAST(RTRIM(trim(cpu), 'm') AS NUMERIC)) AS BIGINT)
		ELSE
			CAST(CAST(trim(cpu) AS NUMERIC) * 1000 AS BIGINT)
	END;
----

Test:

[source, sql]
----
SELECT
	k8s.cpu_m('31750m') = 31750,
	k8s.cpu_m('32') = 32000,
	k8s.cpu_m('1.5') = 1500,
	k8s.cpu_m('1.5m') = 2;
----

Normalize Memory to bytes unit:

[source, sql]
----
CREATE OR REPLACE MACRO k8s.memory_bytes(memory) AS
	CAST(CASE
		WHEN trim(memory) LIKE '%Ki' THEN
			CAST(RTRIM(trim(memory), 'Ki') AS NUMERIC) * 1024
		WHEN trim(memory) LIKE '%Mi' THEN
			CAST(RTRIM(trim(memory), 'Mi') AS NUMERIC) * 1048576
		WHEN trim(memory) LIKE '%Gi' THEN
			CAST(RTRIM(trim(memory), 'Gi') AS NUMERIC) * 1073741824
		WHEN trim(memory) LIKE '%Ti' THEN
			CAST(RTRIM(trim(memory), 'Ti') AS NUMERIC) * 1099511627776
		WHEN trim(memory) LIKE '%Pi' THEN
			CAST(RTRIM(trim(memory), 'Pi') AS NUMERIC) * 1125899906842624
		WHEN trim(memory) LIKE '%Ei' THEN
			CAST(RTRIM(trim(memory), 'Ei') AS NUMERIC) * 1152921504606846976
		WHEN trim(memory) LIKE '%m' THEN
			CEILING(CAST(RTRIM(trim(memory), 'm') AS NUMERIC) / 1000)
		WHEN trim(memory) LIKE '%k' THEN
			CAST(RTRIM(trim(memory), 'k') AS NUMERIC) * 1000
		WHEN trim(memory) LIKE '%M' THEN
			CAST(RTRIM(trim(memory), 'M') AS NUMERIC) * 1000000
		WHEN trim(memory) LIKE '%G' THEN
			CAST(RTRIM(trim(memory), 'G') AS NUMERIC) * 1000000000
		WHEN trim(memory) LIKE '%T' THEN
			CAST(RTRIM(trim(memory), 'T') AS NUMERIC) * 1000000000000
		WHEN trim(memory) LIKE '%P' THEN
			CAST(RTRIM(trim(memory), 'P') AS NUMERIC) * 1000000000000000
		WHEN trim(memory) LIKE '%E' THEN
			CAST(RTRIM(trim(memory), 'E') AS NUMERIC) * 1000000000000000000
		ELSE
			CAST(trim(memory) AS NUMERIC)
	END AS BIGINT);
----

Test:

[source, sql]
----
SELECT
	k8s.memory_bytes('3m') = 1 as subm,
	k8s.memory_bytes('3000m') = 3 as m,
	k8s.memory_bytes('31750') = 31750 AS empty,
	k8s.memory_bytes('32k') = 32000 AS k,
	k8s.memory_bytes('32Ki') = 32768 AS Ki,
	k8s.memory_bytes('10Mi') = 10485760 AS Mi,
	k8s.memory_bytes('1.5Gi') = 1610612736 AS Gi,
	k8s.memory_bytes('1.5Mi') = 1572864 as fraction_Mi;
----

Print the memory back in a human readable form (approximation):

[source, sql]
----
CREATE OR REPLACE MACRO k8s.memory_human(bytes) AS
	CASE
		WHEN CAST(bytes AS DOUBLE) >= (1024::DOUBLE ^ 6) THEN rtrim(printf('%.1f', CAST(bytes AS DOUBLE) / (1024::DOUBLE ^ 6)), '.') || 'Ei'
		WHEN CAST(bytes AS DOUBLE) >= (1024::DOUBLE ^ 5) THEN rtrim(printf('%.1f', CAST(bytes AS DOUBLE) / (1024::DOUBLE ^ 5)), '.') || 'Pi'
		WHEN CAST(bytes AS DOUBLE) >= (1024::DOUBLE ^ 4) THEN rtrim(printf('%.1f', CAST(bytes AS DOUBLE) / (1024::DOUBLE ^ 4)), '.') || 'Ti'
		WHEN CAST(bytes AS DOUBLE) >= (1024::DOUBLE ^ 3) THEN rtrim(printf('%.1f', CAST(bytes AS DOUBLE) / (1024::DOUBLE ^ 3)), '.') || 'Gi'
		WHEN CAST(bytes AS DOUBLE) >= (1024::DOUBLE ^ 2) THEN rtrim(printf('%.1f', CAST(bytes AS DOUBLE) / (1024::DOUBLE ^ 2)), '.') || 'Mi'
		WHEN CAST(bytes AS DOUBLE) >= 1024               THEN rtrim(printf('%.1f', CAST(bytes AS DOUBLE) / 1024), '.') || 'Ki'
		ELSE CAST(bytes AS VARCHAR)
	END;
----

Test:

[source, sql]
----
SELECT
	k8s.memory_human('1') = '1',
	k8s.memory_human('31750') = '31.0Ki' AS empty,
	k8s.memory_human('32000') = '31.2Ki' AS k,
	k8s.memory_human('32768') = '32.0Ki' AS Ki,
	k8s.memory_human('10485760') = '10.0Mi' AS Mi,
	k8s.memory_human('1610612736') = '1.5Gi' AS Gi,
	k8s.memory_human('1572864') = '1.5Mi' as fraction_Mi;
----

== Views

Pod - Node: `pn`

[source, sql]
----
CREATE OR REPLACE VIEW pn AS
	SELECT
		p_kind:p.kind,
		p_apiVersion:p.apiVersion,
		p_name:p.name,
		p_namespace:p.namespace,
		p_metadata:p.metadata,
		p_spec:p.spec,
		p_status:p.status,
		n_kind:n.kind,
		n_apiVersion:n.apiVersion,
		n_name:n.name,
		n_namespace:n.namespace,
		n_metadata:n.metadata,
		n_spec:n.spec,
		n_status:n.status
	FROM nodes AS n
	JOIN pods as p ON n.name = p.spec.nodeName
;
----

Deployment - ReplicaSet - Pod - Node: `drspn`

[source, sql]
----
CREATE OR REPLACE VIEW drspn AS
	SELECT
		d_kind:d.kind,
		d_apiVersion:d.apiVersion,
		d_name:d.name,
		d_namespace:d.namespace,
		d_metadata:d.metadata,
		d_spec:d.spec,
		d_status:d.status,
		rs_kind:rs.kind,
		rs_apiVersion:rs.apiVersion,
		rs_name:rs.name,
		rs_namespace:rs.namespace,
		rs_metadata:rs.metadata,
		rs_spec:rs.spec,
		rs_status:rs.status,
		p_kind:p.kind,
		p_apiVersion:p.apiVersion,
		p_name:p.name,
		p_namespace:p.namespace,
		p_metadata:p.metadata,
		p_spec:p.spec,
		p_status:p.status,
		n_kind:n.kind,
		n_apiVersion:n.apiVersion,
		n_name:n.name,
		n_namespace:n.namespace,
		n_metadata:n.metadata,
		n_spec:n.spec,
		n_status:n.status
	FROM deploy AS d
	JOIN rs ON rs.namespace = d.namespace AND rs.metadata.ownerReferences[1].uid = d.metadata.uid
	JOIN pods AS p ON p.namespace = rs.namespace AND rs.metadata.uid = p.metadata.ownerReferences[1].uid
	LEFT OUTER JOIN nodes as n ON n.name = p.spec.nodeName
;
----

StatefulSet - Pod - Node: `spn`

[source, sql]
----
CREATE OR REPLACE VIEW spn AS
	SELECT
		s_kind:s.kind,
		s_apiVersion:s.apiVersion,
		s_name:s.name,
		s_namespace:s.namespace,
		s_metadata:s.metadata,
		s_spec:s.spec,
		s_status:s.status,
		p_kind:p.kind,
		p_apiVersion:p.apiVersion,
		p_name:p.name,
		p_namespace:p.namespace,
		p_metadata:p.metadata,
		p_spec:p.spec,
		p_status:p.status,
		n_kind:n.kind,
		n_apiVersion:n.apiVersion,
		n_name:n.name,
		n_namespace:n.namespace,
		n_metadata:n.metadata,
		n_spec:n.spec,
		n_status:n.status
	FROM sts AS s
	JOIN pods AS p ON p.namespace = s.namespace AND s.metadata.uid = p.metadata.ownerReferences[1].uid
	LEFT OUTER JOIN nodes as n ON n.name = p.spec.nodeName
;
----
