= bt

== v0.5.0: New features

* Better cache invalidation.

* Suggest workspace completions rather than limiting the list of valid values.

* New command: `bt terraform providers lock`
+
Uses the config file to get the list of archs for the given profile and uses them to update the lock file.

* Add support for missing terraform commands:

** state mv
** validate
** test

== v0.4.0: New features

* Use the default `.terraform/` TF_DATA_DIR when the default profile is used.
Other profiles will continue to use the `.terraform-<profile>/` dir.
+
This eases using Terraform with and without bt.

* Add workspace commands to manage workspaces when working with multiple profiles.
+
When switching to the default workspace, bt automatically removes the environment file so that we are not locked into a specific workspace.

* Expose terraform checks command as a standalone command to allow running pre-apply checks.

== v0.3.0: Breaking changes

Terraform config has been updated to support multiple profiles.

Additionally, the terraform data is no longer saved at the default `.terraform/` dir but has been changed to follow the format `.terraform-<profile>/`.

See the Profiles section in the README for more details.

== v0.2.0: New features and bug fixes

* Bug fix: ensure pre-apply checks run before the apply

* New feature: add --no-checks flag

== v0.1.0: Initial release
