= bt

== v0.10.0: Breaking changes

Updated bt to load config files from the directory by default, this allows to split `bt-stacks` into multiple files.
At least one file named `bt-stacks.cue` is required when using stacks.

* `.bt.cue` config file now requires `package bt` header.

* `bt-stacks.cue` config file now requires `package bt_stacks` header.

== v0.9.0: New features

* Add color flag.

== v0.8.0: New features

* Terraform checks have extra ENV vars exported and can run from parallel stack components.

* Checks can save output to a file.

== v0.7.0: New features

* Add terraform graph wrapper.

* Add option to run terraform providers lock after init.

* Set default parallelism.

* Enable passing variables from stack definition to component.

* Allow running stack from anywhere under the stacks config file.

== v0.6.0: New features

* Introduce stacks and components workflows.

* Ensure plan and apply output files are dir relative.

* Add dry-run flag.

* Add unit tests.

* expand CONFIG_ROOT on init backend config.

* Use default profile for data dir when none selected.

* Ensure quiet controls logging output.

* Remove error on config file not found.

== v0.5.0: New features

* Better cache invalidation.

* Suggest workspace completions rather than limiting the list of valid values.

* New command: `bt terraform providers lock`
+
Uses the config file to get the list of archs for the given profile and uses them to update the lock file.

* Add support for missing terraform commands:

** state mv
** validate
** test

== v0.4.0: New features

* Use the default `.terraform/` TF_DATA_DIR when the default profile is used.
Other profiles will continue to use the `.terraform-<profile>/` dir.
+
This eases using Terraform with and without bt.

* Add workspace commands to manage workspaces when working with multiple profiles.
+
When switching to the default workspace, bt automatically removes the environment file so that we are not locked into a specific workspace.

* Expose terraform checks command as a standalone command to allow running pre-apply checks.

== v0.3.0: Breaking changes

Terraform config has been updated to support multiple profiles.

Additionally, the terraform data is no longer saved at the default `.terraform/` dir but has been changed to follow the format `.terraform-<profile>/`.

See the Profiles section in the README for more details.

== v0.2.0: New features and bug fixes

* Bug fix: ensure pre-apply checks run before the apply

* New feature: add --no-checks flag

== v0.1.0: Initial release
