= bt: Build Terraform

A no commitments Terraform wrapper that provides build caching functionality.

== Install

Install the binary into your `~/go/bin`:

----
go install github.com/DavidGamba/dgtools/bt@latest
----

Then setup the completion.

For bash:

----
complete -o default -C bt bt
----

For zsh:

----
autoload bashcompinit
bashcompinit
complete -o default -C bt bt
----

== Config file

The config file must be saved in a file named `.bt.cue`.
It will be searched from the current dir upwards.

Example:

.Config file .bt.cue
[source, cue]
----
terraform: {
	init: {
		backend_config: ["backend.tfvars"]
	}
	plan: {
		var_file: ["vars.tfvars"]
	}
	workspaces: {
		enabled: true
		dir: "envs"
	}
}
----

== Usage

== Caching Internals

After running `terraform init` it will save a `.tf.init` file.
It will use that file to determine if any files have changed and if re-running is required.

After running `terraform plan` it will save a `.tf.plan` or `.tf.plan-<workspace>` file.
It will use that file to determine if the plan already exists of if needs to be run.

After running `terraform apply` it will save a `.tf.apply` or `.tf.apply-<workspace>` file.
It will use that file to determine if the apply has already been made.
