name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # Build with latest version of Go
  tools:
    name: Tool
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [cli-bookmarks, cssh/cscp, cssh/cssh, ffind, grepp, joinlines, yaml-parse]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -v .
        working-directory: ${{ matrix.tool }}

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
        working-directory: ${{ matrix.tool }}

      - name: Upload
        uses: actions/upload-artifact@v2
        # Workaround to filter out subdirectories, actions don't have a basename function.
        if: ${{ ! contains(matrix.tool, '/') }}
        with:
          name: ${{ matrix.tool }}
          path: ${{ matrix.tool }}/${{ matrix.tool }}

  # Support last two releases of Go
  libs:
    name: Lib
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go : [1.14, 1.15]
        tool: [run]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
        working-directory: ${{ matrix.tool }}
