---
name: Test

on:
  - push
  - pull_request

jobs:

  # Build with latest version of Go
  tools:
    name: Tool
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        tool:
          - cathtml
          - cssh/cscp
          - cssh/cssh
          - clitable/cmd/csvtable
          - grepp
          - joinlines
          - password-cache/cmd/password-cache
          - webserve
          - yaml-parse
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.x
          cache-dependency-path: "**/go.sum"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - id: build
        name: Build
        run: |
          go build -v .
          dir=$(basename $PWD)
          echo "dir: $dir"
          echo "binary=$dir" >> $GITHUB_OUTPUT
        working-directory: ${{ matrix.tool }}
        shell: bash


      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
        working-directory: ${{ matrix.tool }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: ${{ matrix.tool }}/${{ steps.build.outputs.binary }}
          name: ${{ steps.build.outputs.binary }} ${{ matrix.os }}

  # Build with latest version of Go
  tools-linux:
    name: Tool
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tool:
          - cli-bookmarks
          - ffind
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.x
          cache-dependency-path: "**/go.sum"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - id: build
        name: Build
        run: |
          go build -v .
          dir=$(basename $PWD)
          echo "dir: $dir"
          echo "binary=$dir" >> $GITHUB_OUTPUT
        working-directory: ${{ matrix.tool }}
        shell: bash

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
        working-directory: ${{ matrix.tool }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: ${{ matrix.tool }}/${{ steps.build.outputs.binary }}
          name: ${{ steps.build.outputs.binary }} ${{ matrix.os }}

  # Support last two releases of Go
  libs:
    name: Lib
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ["1.21", "1.20"]
        tool: [buildutils, fsmodtime, run]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: "**/go.sum"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
        working-directory: ${{ matrix.tool }}
