= jsql: Run SQL queries on Kubernetes

Runs SQL queries (provided by DuckDB) on Kubernetes JSON outputs.

High level process occurring behind the scenes:

Run: `jsql get -A pods sts deploy nodes replicasets`

jsql will:

* run: `kubectl <resource> -A -o json`
* run `qq .items > <resource>.json` on the output to have a single list of results and save the list into the user's cache dir separated by k8s context.
* run `duckdb` to import the file and auto discover the schema.
* Since this tool focuses on k8s, it will surface the `metadata.name` as `name` and `metadata.namespace` as `namespace` for each of the resources imported.
A node will have a `NULL` namespace, for example, but the query will still work.
* create a few handy <<helper-functions>> and <<views>> for you to use.

Now, you can run `jsql query` or call duckdb directly on the created db `duckdb jsql.duckdb`

`jsql query` will print the results as a json stream because vertical scrolling is easier than horizontal scrolling on a terminal.

You can toggle the output formatting mode:

* `.mode pretty` (default)
* `.mode single_line` (one JSON object per line)

To re-hidrate your data, you can run the `jsql get` command again with each of the resources you want to hidrate.
The rest will stay in place.

To start over or be done, delete the `jsql.duckdb` file.

== Helpful Queries

* Check schema for the columns of a table:
+
[source, sql]
----
select column_name,data_type from duckdb_columns() where table_name = 'pods';
----

* Equivalent of `kubectl get sts -A`
+
[source, sql]
----
SELECT
	name,
	namespace,
	age:k8s.agem(s),
	ready:printf('%d/%d',coalesce(status.readyReplicas,0),spec.replicas),
FROM sts AS s;
----

* Equivalent of `kubectl get deploy -A`
+
[source, sql]
----
SELECT
	name,
	namespace,
	age:k8s.agem(d),
	ready:printf('%d/%d',coalesce(status.readyReplicas,0),spec.replicas),
	up_to_date:coalesce(status.updatedReplicas,0),
	available:coalesce(status.availableReplicas,0)
FROM deploy AS d;
----

* Equivalent of `kubectl get pods -A`
+
[source, sql]
----
SELECT
	name,
	namespace,
	age:k8s.agem(p),
	ready:sum(cs.ready::int),
	phase:status.phase,
	restarts:sum(cs.restartCount),
	restart_age:list(k8s.age(cs.state.running.startedat))
FROM pods AS p
CROSS JOIN unnest(status.containerstatuses) AS t(cs)
WHERE cs.restartCount != 0
GROUP BY name,namespace,age,phase,status
;
----

== Helper Functions

These macros/functions are automatically added by `jsql get`.

They are collected under the `k8s` schema:

[source, sql]
----
CREATE SCHEMA IF NOT EXISTS k8s;
----

=== Get the age of a resource

`k8s.age(x)` will take a timestamp and return a human readable string like `12d`, `3h` or `15m`.
`k8s.agem(x)` will take the resource directly if you are querying a resource table and returns a human readable string like `12d`, `3h` or `15m`.
`k8s.agema(x_metadata)` will take the resource metadata alias if you are querying a view.

[source, sql]
----
CREATE OR REPLACE MACRO k8s.age(x) AS ...;

CREATE OR REPLACE MACRO k8s.mage(x_metadata) AS ...;
----

=== Normalize CPU to m unit so it can be used with aggregation operations

[source, sql]
----
CREATE OR REPLACE MACRO k8s.cpu_m(cpu) AS ...;
----

Test:

[source, sql]
----
SELECT
	k8s.cpu_m('31750m') = 31750,
	k8s.cpu_m('32') = 32000,
	k8s.cpu_m('1.5') = 1500,
	k8s.cpu_m('1.5m') = 2;
----

=== Normalize Memory to bytes unit

[source, sql]
----
CREATE OR REPLACE MACRO k8s.memory_bytes(memory) AS ...;
----

Test:

[source, sql]
----
SELECT
	k8s.memory_bytes('3m') = 1 as subm,
	k8s.memory_bytes('3000m') = 3 as m,
	k8s.memory_bytes('31750') = 31750 AS empty,
	k8s.memory_bytes('32k') = 32000 AS k,
	k8s.memory_bytes('32Ki') = 32768 AS Ki,
	k8s.memory_bytes('10Mi') = 10485760 AS Mi,
	k8s.memory_bytes('1.5Gi') = 1610612736 AS Gi,
	k8s.memory_bytes('1.5Mi') = 1572864 as fraction_Mi;
----

=== Print the memory back in a human readable form (approximation)

[source, sql]
----
CREATE OR REPLACE MACRO k8s.memory_human(bytes) AS ...;
----

Test:

[source, sql]
----
SELECT
	k8s.memory_human('1') = '1',
	k8s.memory_human('31750') = '31.0Ki' AS empty,
	k8s.memory_human('32000') = '31.2Ki' AS k,
	k8s.memory_human('32768') = '32.0Ki' AS Ki,
	k8s.memory_human('10485760') = '10.0Mi' AS Mi,
	k8s.memory_human('1610612736') = '1.5Gi' AS Gi,
	k8s.memory_human('1572864') = '1.5Mi' as fraction_Mi;
----

== Views

These views are automatically added by `jsql get`.

=== Pod - Node: `pn`

[source, sql]
----
CREATE OR REPLACE VIEW pn AS
	SELECT
		p_kind:p.kind,
		p_apiVersion:p.apiVersion,
		p_name:p.name,
		p_namespace:p.namespace,
		p_metadata:p.metadata,
		p_spec:p.spec,
		p_status:p.status,
		n_kind:n.kind,
		n_apiVersion:n.apiVersion,
		n_name:n.name,
		n_namespace:n.namespace,
		n_metadata:n.metadata,
		n_spec:n.spec,
		n_status:n.status
	FROM nodes AS n
	JOIN pods as p ON n.name = p.spec.nodeName
;
----

=== Deployment - ReplicaSet - Pod - Node: `drspn`

[source, sql]
----
CREATE OR REPLACE VIEW drspn AS
	SELECT
		d_kind:d.kind,
		d_apiVersion:d.apiVersion,
		d_name:d.name,
		d_namespace:d.namespace,
		d_metadata:d.metadata,
		d_spec:d.spec,
		d_status:d.status,
		rs_kind:rs.kind,
		rs_apiVersion:rs.apiVersion,
		rs_name:rs.name,
		rs_namespace:rs.namespace,
		rs_metadata:rs.metadata,
		rs_spec:rs.spec,
		rs_status:rs.status,
		p_kind:p.kind,
		p_apiVersion:p.apiVersion,
		p_name:p.name,
		p_namespace:p.namespace,
		p_metadata:p.metadata,
		p_spec:p.spec,
		p_status:p.status,
		n_kind:n.kind,
		n_apiVersion:n.apiVersion,
		n_name:n.name,
		n_namespace:n.namespace,
		n_metadata:n.metadata,
		n_spec:n.spec,
		n_status:n.status
	FROM deploy AS d
	JOIN rs ON rs.namespace = d.namespace AND rs.metadata.ownerReferences[1].uid = d.metadata.uid
	JOIN pods AS p ON p.namespace = rs.namespace AND rs.metadata.uid = p.metadata.ownerReferences[1].uid
	LEFT OUTER JOIN nodes as n ON n.name = p.spec.nodeName
;
----

=== StatefulSet - Pod - Node: `spn`

[source, sql]
----
CREATE OR REPLACE VIEW spn AS
	SELECT
		s_kind:s.kind,
		s_apiVersion:s.apiVersion,
		s_name:s.name,
		s_namespace:s.namespace,
		s_metadata:s.metadata,
		s_spec:s.spec,
		s_status:s.status,
		p_kind:p.kind,
		p_apiVersion:p.apiVersion,
		p_name:p.name,
		p_namespace:p.namespace,
		p_metadata:p.metadata,
		p_spec:p.spec,
		p_status:p.status,
		n_kind:n.kind,
		n_apiVersion:n.apiVersion,
		n_name:n.name,
		n_namespace:n.namespace,
		n_metadata:n.metadata,
		n_spec:n.spec,
		n_status:n.status
	FROM sts AS s
	JOIN pods AS p ON p.namespace = s.namespace AND s.metadata.uid = p.metadata.ownerReferences[1].uid
	LEFT OUTER JOIN nodes as n ON n.name = p.spec.nodeName
;
----
