= jsql: Run SQL queries on JSON and CSV

Runs SQL queries on JSON and CSV generated from Kubernetes, AWS, GitHub, etc with auto inferred schemas courtesy of DuckDB.

The JSON generation is done through providers.
The providers define what command to run to generate the JSON output and how to filter it so it can be consumed as multiple rows.
That JSON output is then passed to DuckDB so that the schema can be auto inferred.

Providers are meant to be easily generated on the fly while allowing you to persist your configuration for reuse.

The SQL input engine allows multiline queries with auto completion.
The queries are stored in history and when recalled, they maintain their multiple lines unlike most SQL interfaces out there.

There are multiple output modes, including a nice looking table mode.
However, the default is a pretty printed JSON stream that allows to visualize very large number of columns as rows while allowing you to leverage the scrollback to navigate all of them without depending on an ultra-wide monitor.

== Installation

* Install using homebrew:
+
----
brew tap DavidGamba/dgtools https://github.com/DavidGamba/dgtools
brew install DavidGamba/dgtools/jsql
----
+
[NOTE]
====
Completion is auto setup for bash.

For `zsh` completions, an additional step is required, add the following to your `.zshrc`:

[source, zsh]
----
export ZSHELL="true"
source "$(brew --prefix)/share/zsh/site-functions/dgtools.jsql.zsh"
----
====
+
Upgrade with:
+
----
brew update
brew upgrade jsql
----

* Install using go:
+
Install the binary into your `~/go/bin`:
+
----
go install github.com/DavidGamba/dgtools/jsql@latest
----
+
Then setup the completion.
+
For bash:
+
----
complete -o default -C jsql jsql
----
+
For zsh:
+
[source, zsh]
----
export ZSHELL="true"
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
complete -o default -C jsql jsql
----

=== Sample Providers

To use a sample provider, copy the file over to the global config directory (`$HOME/.config/jsql/`) or place it in the current working directory.

* link:./aws.cue[AWS Provider]
* link:./github.cue[GitHub Provider]
* link:./k8s.cue[Kubernetes Provider]
* link:./csv.cue[CSV Provider]

== Tutorial

=== Provider Creation

The power of jsql lies in being able to create a custom provider on the fly to analyse data while persisting that config for future reuse.

Providers can be stored globally (`$HOME/.config/jsql/`) or they can live in the current working directory.
Providers are written in link:https://cuelang.org/[CUE], so the file name must have the `.cue` extension.

The first thing to define is how to retrieve the JSON formatted data.

For example, the sample `aws.cue` provider defines the following:

[source, cue]
----
package jsql

provider: aws: {
	getCommands: ebs: {
		command: ["aws", "ec2", "describe-volumes"]
----

It defines a 'Get' command called `ebs` that calls the aws cli to describe ebs volumes.
The output from that aws cli command wraps each result under the `.Volumes` envelope.

[source, json]
----
{
	"Volumes": [
		{
			"VolumeId": "vol-xxx",
			...
		},
		{
			"VolumeId": "vol-yyy",
			...
		}
	]
}
----

To get a stream of elements suitable to be parsed as rows, we add a filter to the provider:

[source, cue]
----
package jsql

provider: aws: {
	getCommands: ebs: {
		command: ["aws", "ec2", "describe-volumes"]
		filter:  ["qq", ".Volumes", "-o", "json"]
----

Finally, all that is left is to load the data onto the DB:

1. Create a wrapper schema to place multiple 'Get' command's data together.
For example `aws`.
This could group `aws.ebs`, `aws.s3`, `aws.ec2`, etc.
2. Create a table under the wrapper schema.
To avoid conflicts with existing data, we first drop the table before creation.
For example `aws.ebs` for this 'Get' command's data.

[source, cue]
----
package jsql

provider: aws: {
	getCommands: ebs: {
		command: ["aws", "ec2", "describe-volumes"]
		filter:  ["qq", ".Volumes", "-o", "json"]
		create: [
			"CREATE SCHEMA IF NOT EXISTS $schemaName;"
			"DROP TABLE IF EXISTS $schemaName.$table"
			"CREATE TABLE $schemaName.$table AS SELECT * FROM '$filename'"
----

You will notice that we introduce `$schemaName`, `$table` and `$filename`. 
These are auto-generated based on the provider and command names but can be overridden if desired.

Finally, you can add custom pieces of logic into your creation steps.
For example, AWS doesn't have a dedicated name field for their resources but it is optionally added as a Tag with key `Name`.
Knowing this, we can add the name column ourselves:

[source, cue]
----
package jsql

provider: aws: {
	getCommands: ebs: {
		command: ["aws", "ec2", "describe-volumes"]
		filter:  ["qq", ".Volumes", "-o", "json"]
		create: [
			"CREATE SCHEMA IF NOT EXISTS $schemaName;"
			"DROP TABLE IF EXISTS $schemaName.$table"
			"CREATE TABLE $schemaName.$table AS SELECT * FROM '$filename'"
			"ALTER TABLE $schemaName.$table ADD COLUMN name VARCHAR;"
			"UPDATE $schemaName.$table SET name = list_filter(Tags, lambda x : x.Key = 'Name')[1].Value;"
		]
	}
}
----

With the provider fully constructed, you can retrieve the data by running: `jsql get aws ebs`

The command will create a `jsql.duckdb` database in the current directory.

Then you can run `jsql query`.

=== Querying

`jsql query` will print the results as a json stream because vertical scrolling is easier than horizontal scrolling on a terminal.

You can toggle the output formatting mode:

* `.mode pretty;` (default) json marshal results
* `.mode table;` pretty print tables and json marshal nested data
* `.mode single_line;` json marshal into one record per line

To re-hidrate your data, you can run the `jsql get` command again with each of the resources you want to hidrate.
The rest will stay in place.

To start over or be done, delete the `jsql.duckdb` file.

=== Helpful Queries

* Check schema for the columns of a table:
+
[source, sql]
----
select column_name,data_type from duckdb_columns() where table_name = 'pods';
----

* Equivalent of `kubectl get sts -A`
+
[source, sql]
----
SELECT
	name,
	namespace,
	age:k8s.agem(s),
	ready:printf('%d/%d',coalesce(status.readyReplicas,0),spec.replicas),
FROM k8s.sts AS s;
----

* Equivalent of `kubectl get deploy -A`
+
[source, sql]
----
SELECT
	name,
	namespace,
	age:k8s.agem(d),
	ready:printf('%d/%d',coalesce(status.readyReplicas,0),spec.replicas),
	up_to_date:coalesce(status.updatedReplicas,0),
	available:coalesce(status.availableReplicas,0)
FROM k8s.deploy AS d;
----

* Equivalent of `kubectl get pods -A`
+
[source, sql]
----
SELECT
	name,
	namespace,
	age:k8s.agem(p),
	ready:sum(cs.ready::int),
	phase:status.phase,
	restarts:sum(cs.restartCount),
	restart_age:list(k8s.age(cs.state.running.startedat))
FROM k8s.pods AS p
CROSS JOIN unnest(status.containerstatuses) AS t(cs)
WHERE cs.restartCount != 0
GROUP BY name,namespace,age,phase,status
;
----

=== Helper Functions

These macros/functions are automatically added by the `jsql get k8s` provider.

=== Get the age of a resource

`k8s.age(x)` will take a timestamp and return a human readable string like `12d`, `3h` or `15m`.
`k8s.agem(x)` will take the resource directly if you are querying a resource table and returns a human readable string like `12d`, `3h` or `15m`.
`k8s.agema(x_metadata)` will take the resource metadata alias if you are querying a view.

[source, sql]
----
CREATE OR REPLACE MACRO k8s.age(x) AS ...;

CREATE OR REPLACE MACRO k8s.mage(x_metadata) AS ...;
----

=== Normalize CPU to m unit so it can be used with aggregation operations

[source, sql]
----
CREATE OR REPLACE MACRO k8s.cpu_m(cpu) AS ...;
----

Test:

[source, sql]
----
SELECT
	k8s.cpu_m('31750m') = 31750,
	k8s.cpu_m('32') = 32000,
	k8s.cpu_m('1.5') = 1500,
	k8s.cpu_m('1.5m') = 2;
----

=== Normalize Memory to bytes unit

[source, sql]
----
CREATE OR REPLACE MACRO k8s.memory_bytes(memory) AS ...;
----

Test:

[source, sql]
----
SELECT
	k8s.memory_bytes('3m') = 1 as subm,
	k8s.memory_bytes('3000m') = 3 as m,
	k8s.memory_bytes('31750') = 31750 AS empty,
	k8s.memory_bytes('32k') = 32000 AS k,
	k8s.memory_bytes('32Ki') = 32768 AS Ki,
	k8s.memory_bytes('10Mi') = 10485760 AS Mi,
	k8s.memory_bytes('1.5Gi') = 1610612736 AS Gi,
	k8s.memory_bytes('1.5Mi') = 1572864 as fraction_Mi;
----

=== Print the memory back in a human readable form (approximation)

[source, sql]
----
CREATE OR REPLACE MACRO k8s.memory_human(bytes) AS ...;
----

Test:

[source, sql]
----
SELECT
	k8s.memory_human('1') = '1',
	k8s.memory_human('31750') = '31.0Ki' AS empty,
	k8s.memory_human('32000') = '31.2Ki' AS k,
	k8s.memory_human('32768') = '32.0Ki' AS Ki,
	k8s.memory_human('10485760') = '10.0Mi' AS Mi,
	k8s.memory_human('1610612736') = '1.5Gi' AS Gi,
	k8s.memory_human('1572864') = '1.5Mi' as fraction_Mi;
----

== Views

These views are automatically added by `jsql get`.

=== Pod - Node: `pn`

[source, sql]
----
CREATE OR REPLACE VIEW pn AS
	SELECT
		p_kind:p.kind,
		p_apiVersion:p.apiVersion,
		p_name:p.name,
		p_namespace:p.namespace,
		p_metadata:p.metadata,
		p_spec:p.spec,
		p_status:p.status,
		n_kind:n.kind,
		n_apiVersion:n.apiVersion,
		n_name:n.name,
		n_namespace:n.namespace,
		n_metadata:n.metadata,
		n_spec:n.spec,
		n_status:n.status
	FROM nodes AS n
	JOIN pods as p ON n.name = p.spec.nodeName
;
----

=== Deployment - ReplicaSet - Pod - Node: `drspn`

[source, sql]
----
CREATE OR REPLACE VIEW drspn AS
	SELECT
		d_kind:d.kind,
		d_apiVersion:d.apiVersion,
		d_name:d.name,
		d_namespace:d.namespace,
		d_metadata:d.metadata,
		d_spec:d.spec,
		d_status:d.status,
		rs_kind:rs.kind,
		rs_apiVersion:rs.apiVersion,
		rs_name:rs.name,
		rs_namespace:rs.namespace,
		rs_metadata:rs.metadata,
		rs_spec:rs.spec,
		rs_status:rs.status,
		p_kind:p.kind,
		p_apiVersion:p.apiVersion,
		p_name:p.name,
		p_namespace:p.namespace,
		p_metadata:p.metadata,
		p_spec:p.spec,
		p_status:p.status,
		n_kind:n.kind,
		n_apiVersion:n.apiVersion,
		n_name:n.name,
		n_namespace:n.namespace,
		n_metadata:n.metadata,
		n_spec:n.spec,
		n_status:n.status
	FROM deploy AS d
	JOIN rs ON rs.namespace = d.namespace AND rs.metadata.ownerReferences[1].uid = d.metadata.uid
	JOIN pods AS p ON p.namespace = rs.namespace AND rs.metadata.uid = p.metadata.ownerReferences[1].uid
	LEFT OUTER JOIN nodes as n ON n.name = p.spec.nodeName
;
----

=== StatefulSet - Pod - Node: `spn`

[source, sql]
----
CREATE OR REPLACE VIEW spn AS
	SELECT
		s_kind:s.kind,
		s_apiVersion:s.apiVersion,
		s_name:s.name,
		s_namespace:s.namespace,
		s_metadata:s.metadata,
		s_spec:s.spec,
		s_status:s.status,
		p_kind:p.kind,
		p_apiVersion:p.apiVersion,
		p_name:p.name,
		p_namespace:p.namespace,
		p_metadata:p.metadata,
		p_spec:p.spec,
		p_status:p.status,
		n_kind:n.kind,
		n_apiVersion:n.apiVersion,
		n_name:n.name,
		n_namespace:n.namespace,
		n_metadata:n.metadata,
		n_spec:n.spec,
		n_status:n.status
	FROM sts AS s
	JOIN pods AS p ON p.namespace = s.namespace AND s.metadata.uid = p.metadata.ownerReferences[1].uid
	LEFT OUTER JOIN nodes as n ON n.name = p.spec.nodeName
;
----
